name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: yarn install
    - name: Unit & e2e Test
      run: yarn run test
      env:
        HEADLESS: true
    - name: Lint
      run: yarn run lint
